### ISSUE TITLE
Create custom navigation bar for profiles

### ISSUE THREAD

**Issue by alicerunsonfedora** [hyperspacedev/labs-swiftui#5]
- [x] I know that I'm requesting a feature for Codename Starlight (SwiftUI) and not for Hyperspace Desktop (JS).

**Is your feature request related to a problem? Please describe.**

The NavigationView we're using to create custom profiles is a bit wonky and doesn't work as well as we expected.

**Describe the solution you'd like**

We should make a custom `NavigationView` (iOS only) that will mitigate some of these issues.

**Describe alternatives you've considered**

- Using ScrollView: Not working as intended.

**Additional context**

No other contexts.

**Comment by alexmodrono** [comment]
Fixed by commit 87cfefb89da43732ed23e1327458632cd3b1bc44.
