### ISSUE TITLE
Render sanitized HTML

### ISSUE THREAD

**Issue by alexmodrono** [hyperspacedev/labs-swiftui#6]
- [x] I know that I'm requesting a feature for Codename Starlight (SwiftUI) and not for Hyperspace Desktop (JS).

**Is your feature request related to a problem? Please describe.**

While statuses currently look pretty good, posts with lots of HTML look like a mess.

**Describe the solution you'd like**

We need to find a way to render HTML to make statuses that don't give you a stroke while reading them, and also provide a way to interact with its content (tags, links, etc.), probably by using deep link handlers (?).

**Describe alternatives you've considered**

1. We can use [iwasrobbed's Down](https://github.com/iwasrobbed/Down/) to try to render Mastodon's sanitized HTML to NSAttributedStrings.

2. We can implement a custom function as an extension to Strings to render them. For example:
```swift
extension String {
    func htmlAttributedString() -> NSAttributedString? {
        guard let data = self.data(using: String.Encoding.utf16, allowLossyConversion: false) else { return nil }
        guard let html = try? NSMutableAttributedString(
            data: data,
            options: [NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType],
            documentAttributes: nil) else { return nil }
        html.beginEditing()
        html.enumerateAttribute(NSFontAttributeName, in: NSMakeRange(0, html.length), options: .init(rawValue: 0)) {
            (value, range, stop) in
            if let font = value as? UIFont {
                let resizedFont = font.withSize(font.pointSize * 0.75)
                html.addAttribute(NSFontAttributeName,
                                         value: resizedFont,
                                         range: range)
            }
        }
        html.endEditing()
        return html
    }
}

let htmlStr: String = "<font size=\"6\">font a</font><font size=\"16\">Font b</font>"
let attriStr: NSAttributedString? = htmlStr.htmlAttributedString()
```

**Additional context**

<img width="584" alt="Screenshot 2020-07-15 at 17 33 48" src="https://user-images.githubusercontent.com/28487357/87564990-5a0cd680-c6c1-11ea-9888-6ee1b56bbe0f.png">
Here's how posts with links and tags look like.

**Comment by alicerunsonfedora** [comment]
Should be all set with latest commit, but we'll need to figure out the bounds for macOS variants (and maybe iPadOS, too... 🤔 )

![IMG_5582A3729F45-1](https://user-images.githubusercontent.com/13445064/87879670-642d1e80-c9ba-11ea-8995-359e8ea3076b.jpeg)

**Comment by alicerunsonfedora** [comment]
Superseded by #19.
