### ISSUE TITLE
App crashes when there's no available internet connection.

### ISSUE THREAD

**Issue by alexmodrono** [hyperspacedev/labs-swiftui#7]
- [x] I know that I'm reporting a bug for Codename Starlight (SwiftUI) and not for Hyperspace Desktop (JS).

**Describe the bug**

When opening the app without being connected to the internet, it crashes because `AppClient` can't decode the JSON data to the data models, mostly because there's no data to decode.

Currently, there's a function to detect whether there's an available connection (`isConnectedToNetwork()`), I guess we can make the `defaultInstance` singleton return an error message or `nil` if `isConnectedToNetwork()` is not `true`.

**To Reproduce**

1. Disable Wifi/Data or enter Airplane mode.
2. Open the app
3. Enjoy the app crashing.
4. ?
5. Profit.

**Expected behavior**

I expect the app to don't crash. 

**Screenshots**

**App Information (please complete the following information):**

-   OS: iOS
-   Version: 14 beta 2
-   Is Jailbroken (when applicable)

**Additional context**

```swift
let request = makeAuthenticatedRequest(url: "/api/v1/notifications")
URLSession.shared.dataTask(with: request) { (data, _, error) in
    if error != nil {
        print("Error: \(error as Any)")
    }
    DispatchQueue.main.async {
        do {
            let results = try JSONDecoder().decode([Notification].self, from: data!) // This line causes the crash because 'data' is nil, because URLSession couldn't complete the request.
            completion(results)
        } catch {
            print("Error: \(error)")
        }
    }
}
.resume()
```

**Comment by alexmodrono** [comment]
Alright, so while this issue is tagged with **can wait**, I think it is very important that we fix it because it is caused by a logic problem with the actual's app workflow. 

I'm writing this comment just to discuss some of the options we have on how to tackle this bug. Also, I've been a bit busy these days, so if anyone wants to start working on it, they can use this as a guide.

## The problem

One of the hardest things when building apps and designing systems is deciding how to model and deal with the state of the data you're retrieving. Code managing state is also a very common source of bugs when parts of our app might end up in a state we didn't expect. But in this specific case, the app crashes because the `JSONDecoder` tries to decode the data retrieved by the `URLSession` into an array of a specific data model, but since there's no internet connection, there's no data to decode.

This issue is not specific to just not having an available internet connection since `URLSession` can fail due to multiple reasons, so we need to handle errors (so that the app doesn't crash), and we need to perform a series of checks to make sure there's an available internet connection, for example. The thing is that you should never need to check for multiple conditions to determine what state you are in, so one core principle that is good to keep in mind when modeling various states is to try to stick to a "single source of truth" as much as possible.

## Our situation

Let's say this is our app's workflow:
<img src="https://user-images.githubusercontent.com/28487357/95014669-a58faa80-0648-11eb-85f8-60b5f774f054.png" height="1000" align="center">

There are no checks to whether the data could be retrieved successfully. Right now, if no data can be retrieved, either the app will crash, or the feed will just display placeholder statuses forever, without any indication telling that the statuses could not be retrieved, which is a really bad UX.

Ideally, our workflow should be like this:

![Starlight's app flow](https://user-images.githubusercontent.com/28487357/95010493-15db0380-062a-11eb-98cb-2075df204c90.png)

## The solution: modeling state

My solution to this is having a modeling state `enum` that will allow us to quickly monitor the state the data is at, and avoid unexpected behavior.

### Example

```swift
public class Status: Codable, Identifiable {

    // [...] Here go all the status properties...

    enum State {
        case willLoad
        case loading(message: String)
        case success(statuses: [Status])
        case failure(message: String)
    }

    var state: State = .willLoad
}
```

So now, we can do the following:
<img src="https://user-images.githubusercontent.com/28487357/95014839-ea681100-0649-11eb-9cbf-acd4c2d8abcc.png" height="1000" align="center">

And our code would be like this:
```swift
let request = makeAuthenticatedRequest(url: "/api/v1/statuses")
let state: Status.state = .loading(message: "Loading statuses...")
URLSession.shared.dataTask(with: request) { (data, _, error) in
    if error != nil {
        completion(.failure("An unexpected error happened: \(error as Any)."))
    }
    DispatchQueue.main.async {
        do {
            let results = try JSONDecoder().decode([Status].self, from: data!)
            completion(.success(statuses: results))
        } catch {
            completion(.failure("An unexpected error happened: \(error as Any)."))
        }
    }
}
.resume()
```

And then, on our StatusViewModel, we can do the following:
```swift
private func resolveStatuses() {
    // The status array for the feed is declaratively resolved directly from the state
    switch state {
    case .loading(let message):
        self.loading = message
    case .success(let statuses):
        self.statuses = statuses
    case .failure(let message):
        self.failure = message
    }
}
```

## Progress indications
Another problem we have is that there's no way for the user to know whether the app is doing something or has just stopped working. I've been designing a library that allows displaying toasts similar to those used by Apple in iOS 13 when you disable silent mode, which I think we can use to tell the user what's the app doing in the background.

![IMG_F73A5B25E768-1](https://user-images.githubusercontent.com/28487357/95015577-f950c280-064d-11eb-9f48-0e6a26ca8396.jpeg)

In this case, we can use both the `.loading` and `.failure` states to display an alert using the message provided.

## Conclusion

What do you guys think about this? Is there any other way you think would be better for solving this?

**Comment by alicerunsonfedora** [comment]
This seems like an interesting approach to take with handling states. I wonder if we can make a base struct or protocol that our data models can conform to so that we can modularize it.

**Comment by alicerunsonfedora** [comment]
Alright, I've made a base class for state representation, StateRepresentable.

**Comment by alexmodrono** [comment]
Alright so after working on another app that had the same problem, I found another way to solve this problem. Instead of using states, I found out that using combine and subscribing for any errors was more effective, and easier to implement.

Because of this, I had to rewrite the AppClient class, and adapt our code to the new methods. All of this will happen at the [/state-management](https://github.com/hyperspacedev/starlight/tree/data/state-management) branch.

**Comment by alicerunsonfedora** [comment]
That definitely sounds more like the "Swifty" way of doing things. I wonder if this will allow us to take advantage of the future `async`/`await` features that recently were approved...

For reference: https://forums.swift.org/t/accepted-with-modification-se-0296-async-await/43318

**Comment by alexmodrono** [comment]
We are still using states though. It might be good to develop a library for displaying toasts in SwiftUI, similar to [Bauletto](https://github.com/gianpispi/Bauletto), but supporting macOS.

>  I wonder if this will allow us to take advantage of the future async/await features that recently were approved...

I guess so. This was the most _swiftly_ way I could think of for achieving this since it makes use of Apple's powerful networking methods such as `URLSession`, and also uses combine, which would allow easily implement newer features.

**Comment by alicerunsonfedora** [comment]
I believe this issue has been resolved since we're using state-driven management in combination with the async/await features from Swift 5.5. I will close this for now.
